version: "3.9"
services:
  bot:
    build: .
    env_file:
      - .env
  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/db.sql